name: Log Commit Information

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log commit information
      run: |
        echo "Commit Message: ${{ github.event.head_commit.message }}" >> commits
        echo "Commit SHA: ${{ github.sha }}" >> commits
        echo "User Name: ${{ github.event.head_commit.author.name }}" >> commits
        echo "Branch Name: ${{ github.ref }}" >> commits
        echo "Repo Name: ${{ github.repository }}" >> commits
        echo "Runner Name: ${{ github.run_id }}" >> commits

    - name: Slack Messaging
     # You may pin to the exact commit or the version.
  # uses: wearerequired/slack-messaging-action@27b8384cb9ffad7232beb8a4ecdfbb47a19efebf
      uses: wearerequired/slack-messaging-action@v2.0.2
      with:
    # The Slack bot token.
         bot_token: xoxb-5162951814370-5186692936000-rSQLbgJpkEcU0vLEyeWKsYIa
    # The Slack channel name. Required if no `channel_id` provided
         payload: hi there
         slack-channel: test

