name: Log Commit Information

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log commit information
      run: |
        echo "Commit Message: ${{ github.event.head_commit.message }}" >> DevOpsHome/commit_information.txt
        echo "Commit SHA: ${{ github.sha }}" >> DevOpsHome/commit_information.txt
        echo "User Name: ${{ github.event.head_commit.author.name }}" >> DevOpsHome/commit_information.txt
        echo "Branch Name: ${{ github.ref }}" >> DevOpsHome/commit_information.txt
        echo "Repo Name: ${{ github.repository }}" >> DevOpsHome/commit_information.txt
        echo "Runner Name: ${{ github.run_id }}" >> DevOpsHome/commit_information.txt
