name: Log Commit Information

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log commit information
      run: |
        echo "Commit Message : ${{ github.event.head_commit.message }}" >> commits.txt
        echo "Commit SHA     : ${{ github.sha }}" >> commits.txt
        echo "User Name      : ${{ github.event.head_commit.author.name }}" >> commits.txt
        echo "Branch Name    : ${{ github.ref }}" >> commits.txt
        echo "Repo Name      : ${{ github.repository }}" >> commits.txt
        echo "Runner Name    : ${{ github.run_id }}" >> commits.txt

    - name: Slack Message
      uses: adrey/slack-file-upload-action@master
      with:
        token: xoxb-5162951814370-5165413833939-rNOmuF7jypbUvQyqUEzY0Tpo
        path: commits.txt
        channel: test
        initial_comment: "test"


