name: Log Commit Information

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set commit information as environment variables
      run: |
        echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
        echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "USER_NAME=${{ github.event.head_commit.author.name }}" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV
        echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
        echo "RUNNER_NAME=${{ github.run_id }}" >> $GITHUB_ENV

    - name: Create commit_information.txt file
      run: |
        touch commit_information.txt
        echo "Commit Message: ${{ env.COMMIT_MESSAGE }}" > commit_information.txt
        echo "Commit SHA: ${{ env.COMMIT_SHA }}" >> commit_information.txt
        echo "User Name: ${{ env.USER_NAME }}" >> commit_information.txt
        echo "Branch Name: ${{ env.BRANCH_NAME }}" >> commit_information.txt
        echo "Repo Name: ${{ env.REPO_NAME }}" >> commit_information.txt
        echo "Runner Name: ${{ env.RUNNER_NAME }}" >> commit_information.txt
